---
# Source: helm-nodejs-express/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: simple-express-dev
  namespace: default
spec:
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
  selector:
    app: simple-express-dev
---
# Source: helm-nodejs-express/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express-dev
  namespace: default
  labels:
    name: simple-express-dev

spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express-dev
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  
  template:
    metadata:
      labels:
        app: simple-express-dev
    
    spec:
      containers:
      - name: simple-express-dev
        image: hidetran/simple-express:dev
        imagePullPolicy: Always
        command: ["/bin/sh", "-ce", "export PORT=6000; npm install; node index.js;"]
        
        ports:
          - containerPort: 6000
            protocol: TCP
        
        readinessProbe:
          httpGet:
             path: /
             port: 6000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
        
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "sleep 10"]

        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 250m
